### ISSUE TITLE
请问为什么会提示编译器设置不正确，我完全按照readme的步骤正确设置了路径

### ISSUE THREAD

**Issue by killer-p** [KatyushaScarlet/hifive1-revb#2]
请问为什么会提示编译器设置不正确，我完全按照readme的步骤正确设置了路径
![image](https://user-images.githubusercontent.com/54734292/83713557-f5d70b80-a65a-11ea-9ebd-33ed94aa8050.png)
最终没有生成最终文件

**Comment by haodongnj** [comment]
可以尝试使用rt-thread的env tool来编译。我这边即使再Sconscript中没有配置好路径，env tool也带了编译器。
![env_tool](https://user-images.githubusercontent.com/9603572/88460631-1ccdf300-ced0-11ea-8bb7-1cfbe1328be3.png)

**Comment by haodongnj** [comment]
> 
> 
> 可以尝试使用rt-thread的env tool来编译。我这边即使再Sconscript中没有配置好路径，env tool也带了编译器。
> ![env_tool](https://user-images.githubusercontent.com/9603572/88460631-1ccdf300-ced0-11ea-8bb7-1cfbe1328be3.png)

env tool 并没有自带编译器（是我以前把编译器加入系统环境变量了，可以试试加入环境变量）
